### ISSUE TITLE
TypeError: 'mappingproxy' object is not callable

### ISSUE THREAD

**Issue by alex-vyverman** [rrooggiieerr/homeassistant-nad#1]
Hi @rrooggiieerr 

I saw your post in [https://github.com/joopert/nad_receiver/issues/57](https://github.com/joopert/nad_receiver/issues/57)
It looked exactly what I was looking for.
Unfortunatly, when trying out the custom component I run into this error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nad/__init__.py", line 212, in async_setup_entry
    receiver_coordinator = NADReceiverCoordinator(hass, entry)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nad/__init__.py", line 83, in __init__
    host = self.config(CONF_HOST)
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'mappingproxy' object is not callable
```

Any idea's where it comes from or how to fix it?

**Comment by rrooggiieerr** [comment]
Hi @alex-vyverman, thanks for the feedback! I'm using the serial interface myself, so never ran into this issue. The problem was quite obvious for me, so I quickly fixed it. I also had some other changes in my own codebase which I also pushed to GitHub, so give the latest code a try and let me know how that works for you

**Comment by alex-vyverman** [comment]
Thanks for the quick respons @rrooggiieerr !
I tried the integration, but it seems you try to import the Class `NADCommandNotSupportedError`, but there is no such class in `nad_receiver`
Maybe I'm using a wrong version, or was this implemented in another version of the lib?

Many thanks!

**Comment by rrooggiieerr** [comment]
Can you try again with the latest code?

**Comment by alex-vyverman** [comment]
Yes, now it seems to work perfectly!
<img width="1060" alt="Screenshot 2024-02-20 at 20 00 27" src="https://github.com/rrooggiieerr/homeassistant-nad/assets/50447785/a0448e99-7eb8-4f23-bc96-bf7008e01dca">

**Comment by rrooggiieerr** [comment]
That's great! Using the network connection?

Does your Source and Sound mode also work?
<img width="586" alt="Screenshot 2024-02-20 at 20 12 18" src="https://github.com/rrooggiieerr/homeassistant-nad/assets/18603534/5c415586-edc4-48d2-a098-0b00f40d6696">

I only developed controls and sensors for the features my T755 supports. If you're missing some feel free to add them in the code and create a pull request with the changes.

**Comment by alex-vyverman** [comment]
Hey @rrooggiieerr 
I'm using the telnet connection
No, sound mode and source don't seem to work on my T758 v3. 


I indeed see differences in the calls you make, compaired to what my receiver wants.
If I for instance do a `Main.listeningMode?` in telnet I get:
```
Main.ListeningMode=DolbySurround
Main.ListeningMode.Analog=DolbySurround
Main.ListeningMode.DTS.Stereo=NeuralX
Main.ListeningMode.DTS.Surround=None
Main.ListeningMode.Dolby.Stereo=DolbySurround
Main.ListeningMode.Dolby.Surround=None
Main.ListeningMode.PCM.Stereo=DolbySurround
Main.ListeningMode.PCM.Surround=None
```

Which differs from your entries:

```
        SelectEntityDescription(
            key="Main.ListeningMode.Analog",
            name="Analog Signal Listening Mode",
            options=[
                "None",
                "ProLogic",
                "PLIIMovie",
                "PLIIMusic",
                "NEO6Cinema",
                "NEO6Music",
                "EARS",
                "EnhancedStereo",
                "AnalogBypass",
            ],
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
        ),
        SelectEntityDescription(
            key="Main.ListeningMode.Digital",
            name="Digital Signal Listening Mode",
            options=[
                "None",
                "ProLogic",
                "PLIIMovie",
                "PLIIMusic",
                "NEO6Cinema",
                "NEO6Music",
                "EARS",
                "EnhancedStereo",
                "StereoDownmix",
            ],
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
        ),
        SelectEntityDescription(
            key="Main.ListeningMode.DolbyDigital",
            name="Dolby Digital Listening Mode",
            options=["None", "PLIIMovie", "PLIIMusic", "SurroundEX", "StereoDownmix"],
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
        ),
        SelectEntityDescription(
            key="Main.ListeningMode.DolbyDigital2ch",
            name="Dolby Digital 2 channel Listening Mode",
            options=["None", "ProLogic", "PLIIMovie", "PLIIMusic"],
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
        ),
        SelectEntityDescription(
            key="Main.ListeningMode.DTS",
            name="DTS Listening Mode",
            options=["None", "NEO6Music", "StereoDownmix"],
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
```


Which explains why only `Main.ListeningMode.Analog` works in HA.

Before I do stupid things, how does your discovery of options work?

**Comment by rrooggiieerr** [comment]
Sorry for not getting back to you earlier. Options are not discovered, they are currently hard coded for my T755. Commands are detected though, the code tries out a command during initialisation of the integration, and if the command fails the entity for that command is not added.

    for entity_description in entity_descriptions:
        if coordinator.supports_command(entity_description.key):
            entities.append(NADReceiverSensor(coordinator, entity_description))

https://github.com/rrooggiieerr/homeassistant-nad/blame/117f1488452ea561d30c41b7a9f136f7b4b3e654/custom_components/nad/sensor.py#L77-L79

**Comment by rrooggiieerr** [comment]
Hi Alex, I recently picked up a T757 and want to improve my integration for this device. But first I need to connect to it. Did you do anything special to connect to your T758? I don't get any response when connecting to the serial port

**Comment by rrooggiieerr** [comment]
Never mind, it's working. Loose connector inside the receiver I guess
